version: '3.9'
services:
  web:
    build:
      context: .
      target: dev
    ports:
      - 9000:8080
      - 9229:9229 # debugger
    environment:
      CaptchaEnabled: false
      CaptchaFieldName: cfTurnstileResponse
      CaptchaSecretKeyParameterPath: '/cloudflare/ContactFormHandler/TURNSTILE_SECRET_KEY'
      EmailSubjectSuffix: ${EMAIL_SUBJECT_SUFFIX}
      ValidatedEmailAddress: ${EMAIL_TO_ADDRESS}
    volumes:
      - ~/.aws:/root/.aws:ro # AWS credentials
      - ./dist:/var/task
      - ./node_modules:/var/task/node_modules
